language: qml
services:
- docker
before_install:
- docker pull homdx/qt-sources:001-slim
- rm -rvf binapk
- mkdir source
- cd source
- git clone https://github.com/homdx/qt-view
- cd qt-view
script:
- docker build -t test .
- mkdir apk
- docker run --rm -it --name test -v $TRAVIS_BUILD_DIR/source/qt-view/apk:/app2 -d
  test
- docker exec -it test cp /app/android-build-debug.apk /app2/dev-preview.apk
- ls -la apk
- mv apk/dev-preview.apk $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: FrgQMI2NxMUzwOvSHacS+lYFt4cIsMgRjQzX3+XRHmVfZlNXpBIsJpZeH31NP23mxZGWdBfxLl0StbucLdQmUg9P84H2twBtgIzRbybsUkl8NEi+0jtyDC0PKC9an+dpWZnR+eIbcRw9xEusuOfdv/02m2D2J47moHxajOodS0UUgh0vvY85wUIA7V6MkejV7RMU3nG/m2rEtmxJ4t0nibJQvOC8+ovViSxRyOvExmsdZKj0JYuLfFHICyqxHmbGZ6/qVf3QFYO6KEqhArWIxJZ+zQHr/HfiCLWMvZcjdZn40kxEwEa2O634+fXqchQNMNFiitMKJ88RDRo2PyWesEB2LNSY2HxdtMQpjVLkHNhuz4uxAUmCdD9m38HlhvytKT0+HVOMWdhTcxXYKik7kVFCjNaAtVbry1w9ixvHmBdtY4LjTRdjO5oZJFtHI4q5tKhaE5WVERuT9sPWiOT8KFvqRBRvlh2BYshbXNuBk/d5rWANynwuJnYT3biwlLZmNSHpRsdHfUMHNaqFvS4X6MJ+lvgoNEyMH3xEKrVvQbGYHLbjfM8u4k8fUff2rZ+Rg9yrGcFSXALtSzYhhj/n1oSsIkYBRE0MS9ApcTUe250yQbSkgK/d2pgpNNbmhPqCWxTuFZXzuQ/uIYpSNzHgKKCe3Jnr4qcWmHQR45cMHsg=
  file:
    - dev-preview.apk
  prerelease: true
  skip_cleanup: true
  draft: true
  on:
    repo: flytrue/dev-apk1
